export const optionMenuConstants = Object.freeze({
  OPTIONS_API_START: "OPTIONS_API_START",
  OPTIONS_API_SUCCESS: "OPTIONS_API_SUCCESS",
  OPTIONS_API_FAILED: "OPTIONS_API_FAILED",
});

export const booksConstants = Object.freeze({
  BOOKS_API_START: "BOOKS_API_START",
  BOOKS_API_SUCCESS: "BOOKS_API_SUCCESS",
  BOOKS_API_UPDATE_PAGE_CONTROLS: "BOOKS_API_UPDATE_PAGE_CONTROLS",
  BOOKS_API_FAILED: "BOOKS_API_FAILED",
  BOOKS_API_FETCH_MORE_DATA: "BOOKS_API_FETCH_MORE_DATA",
  BOOKS_API_FETCH_MORE_DATA_SUCCESS: "BOOKS_API_FETCH_MORE_DATA_SUCCESS",
});

export const mainApi = Object.freeze({
  url: "https://www.anapioficeandfire.com/api",
});
